site_name: Documents
site_url: https://document.eduardanderegg.ch
theme:
  name: material
  icon:
    annotation: material/application-braces-outline
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.tabs
    - header.autohide
    - navigation.top
    - content.code.copy
    - content.code.select
    - content.tabs.link
markdown_extensions:
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - tables
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
nav:
  - Home:
      - index: ./index.md
  - Webtechnologie:
      - CSS_Basic: ./Webtechnologie/CSS_Basic.md
      - CSS_Bild_Transformationen_Animationen: ./Webtechnologie/CSS_Bild_Transformationen_Animationen.md
      - CSS_Layoutgestaltung: ./Webtechnologie/CSS_Layoutgestaltung.md
      - CSS_Responsive_Web_Design: ./Webtechnologie/CSS_Responsive_Web_Design.md
      - HTML: ./Webtechnologie/HTML.md
      - Webprotokolle: ./Webtechnologie/Webprotokolle.md
      - Webservice_XAMPP: ./Webtechnologie/Webservice_XAMPP.md
  - Programmierung:
      - DieSprache: ./Programmierung/DieSprache.md
      - Klasse: ./Programmierung/Klasse.md
      - MVC: ./Programmierung/MVC.md
  - Unix:
      - Aufbau: ./Unix/Aufbau.md
      - Geschichte: ./Unix/Geschichte.md
      - Linux: ./Unix/Linux.md
  - Netzwerk:
      - Datenuebertragung: ./Netzwerk/Datenuebertragung.md
      - IP-Adresse: ./Netzwerk/IP-Adresse.md
      - OSI-Schichtenmodell: ./Netzwerk/OSI-Schichtenmodell.md
      - Switch: ./Netzwerk/Switch.md
      - SwitchKonfig: ./Netzwerk/SwitchKonfig.md
      - Topologien: ./Netzwerk/Topologien.md
      - Verkabelung: ./Netzwerk/Verkabelung.md
      - Zugriffsverfahren: ./Netzwerk/Zugriffsverfahren.md
copyright: "Version: ${BUILD_VERSION}"


























































































































































